version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "parse-server"
      - dependency-name: "@sendgrid/mail"
      - dependency-name: "aws-sdk"
      - dependency-name: "body-parser"
      - dependency-name: "braintree"
      - dependency-name: "cookie-parser"
      - dependency-name: "crypto-js"
      - dependency-name: "ejs"
      - dependency-name: "express"
      - dependency-name: "jsonwebtoken"
      - dependency-name: "mailgun-js"
      - dependency-name: "mandrill-api"
      - dependency-name: "mercadopago"
      - dependency-name: "method-override"
      - dependency-name: "moment"
      - dependency-name: "numeral"
      - dependency-name: "parse-cache"
      - dependency-name: "parse-express-cookie-session"
      - dependency-name: "parse-express-https-redirect"
      - dependency-name: "parse-image"
      - dependency-name: "plivo"
      - dependency-name: "pug"
      - dependency-name: "pusher"
      - dependency-name: "stripe"
      - dependency-name: "twilio"
      - dependency-name: "underscore"
      - dependency-name: "xlsx"
